public class AccountManagerHandler {
    public void beforeInsert(List<Account> records) {

    }

    public void beforeUpdate(List<Account> records) {

    }

    public void beforeDelete(List<Account> records) {

    }

    public void afterInsert(List<Account> records) {

    }

    public void afterUpdate(List<Account> records) {

    }

    public void afterDelete(List<Account> records) {

    }
}